In [ ]:
# Q1 Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [24]:
import numpy as np
array = np.arange(2,50,3)
array

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [ ]:
# Q2 Accept two lists of 5 elements each from the user.
# Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [14]:
list_1 = [4,1,5,6,2]
list_2 = [9,12,8,16,23]
array_1 = np.array(list_1)
array_2 = np.array(list_2)
concat_array = np.concatenate((array_1,array_2))
print(concat_array)
sort_array = np.sort(concat_array)
print(sort_array)

[ 4  1  5  6  2  9 12  8 16 23]
[ 1  2  4  5  6  8  9 12 16 23]


In [ ]:
# Q3 Write a code snippet to find the dimensions of a ndarray and its size.

In [17]:
ndarray = ([[1,2,3],[4,5,6],[7,8,9]])
print(np.ndim(ndarray))
print(np.size(ndarray))

2
9


In [ ]:
# Q4 How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
# Hint: np.newaxis, np.expand_dims

In [19]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
# Q5 Consider two square numpy arrays. Stack them vertically and horizontally.
# Hint: Use vstack(), hstack()

In [22]:
f = np.array([1,2,3])
g = np.array([4,5,6])

print(np.hstack((f, g)))
print(np.vstack((f, g)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Q6 How to get unique items and counts of unique items?

In [23]:
a = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print("Original array:")
print(a)
unique_elements, counts_elements = np.unique(a, return_counts=True)
print(unique_elements)
print(counts_elements)

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
[10 20 30 40 50]
[3 4 2 2 1]
